"use client";

import { useState } from "react";
import localFont from "next/font/local";
import Link from "next/link";
import Image from "next/image";
import "./globals.css";

const ABCDiatypeMono = localFont({
  src: "./fonts/ABCDiatypeMonoVariable.ttf",
  variable: "--abc-diatype-mono",
});

// export const metadata = {
//   title: "Archivo Público",
//   description: "Generated by create next app",
// };

// AL SACAR MENU DE LAYOUT, DESCOMENTAR LA METADATA Y SACAR `USE CLIENT`

export default function RootLayout({ children }) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const handleMenu = () => {
    setIsMenuOpen((prevState) => !prevState);
  };

  return (
    <html lang="en">
      <body className={`${ABCDiatypeMono.variable}`}>
        <div className="container">
          <header>
            <div className="header-wrap">
              <nav
                className={`${isMenuOpen ? 'open' : ''}`}
              >
                <ul>
                  <li>
                    <Link href="/">SHOP</Link>
                  </li>
                  <li>
                    <Link href="/">ABOUT</Link>
                  </li>
                  <li>
                    <Link href="/">WEBSITE-TERMS</Link>
                  </li>
                  <li>
                    <Link href="/">E-MAIL</Link>
                  </li>
                  <li>
                    <Link href="/">INSTAGRAM</Link>
                  </li>
                  <li>
                    <Link href="/">CART (0)</Link>
                  </li>
                </ul>
              </nav>
              <div className="logo">
                <Link href="/">
                  <Image
                    src="/images/logotipo_ap.png"
                    alt="Logotipo de Archivo Público"
                    layout="responsive"
                    width={400}
                    height={56}
                    priority
                  />
                </Link>
              </div>
              <div className="iso-full">
                <Image
                  src="/images/iso_full_ap.png"
                  alt="Isotipo de Archivo Público"
                  layout="responsive"
                  width={173}
                  height={600}
                  priority
                />
              </div>
              <div className="iso-simple" onClick={handleMenu}>
                <Image
                  src={
                    isMenuOpen
                      ? "/images/iso_mobile_open.png"
                      : "/images/iso_mobile_close.png"
                  }
                  alt="Isotipo de Archivo Público"
                  layout="responsive"
                  width={50}
                  height={50}
                  priority
                />
              </div>
            </div>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
